services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: food-promotion-frontend
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules